
from PyQt5 import QtCore, QtGui, QtWidgets
import hashes

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(468, 521)
        MainWindow.setWindowOpacity(0.9)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MainLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(52)
        font.setItalic(True)
        self.MainLabel.setFont(font)
        self.MainLabel.setObjectName("MainLabel")
        self.gridLayout.addWidget(self.MainLabel, 0, 0, 1, 2)
        self.mainIcon = QtWidgets.QLabel(self.centralwidget)
        self.mainIcon.setMaximumSize(QtCore.QSize(100, 50))
        self.mainIcon.setText("")
        self.mainIcon.setPixmap(QtGui.QPixmap("icons/alg.png"))
        self.mainIcon.setScaledContents(True)
        self.mainIcon.setObjectName("mainIcon")
        self.gridLayout.addWidget(self.mainIcon, 0, 2, 1, 1)
        self.encButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Nueva Std")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.encButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.encButton.setIcon(icon)
        self.encButton.setObjectName("encButton")
        self.gridLayout.addWidget(self.encButton, 1, 2, 1, 1)
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 2, 2, 1, 1)
        self.exitButton.clicked.connect(self.quit)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 3)
        self.loadFileLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        font.setItalic(False)
        self.loadFileLabel.setFont(font)
        self.loadFileLabel.setObjectName("loadFileLabel")
        self.gridLayout.addWidget(self.loadFileLabel, 4, 0, 1, 1)
        self.CalculateButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.CalculateButton.setFont(font)
        self.CalculateButton.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.CalculateButton.setObjectName("CalculateButton")
        self.CalculateButton.clicked.connect(self.calculate)
        self.gridLayout.addWidget(self.CalculateButton, 4, 2, 1, 1)
        self.fileLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.gridLayout.addWidget(self.fileLineEdit, 5, 0, 1, 2)
        self.fileButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileButton.setObjectName("fileButton")
        self.fileButton.clicked.connect(self.file_dialogue)
        self.gridLayout.addWidget(self.fileButton, 6, 0, 1, 1)
        self.EnterStringLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        font.setItalic(False)
        self.EnterStringLabel.setFont(font)
        self.EnterStringLabel.setObjectName("EnterStringLabel")
        self.gridLayout.addWidget(self.EnterStringLabel, 7, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 7, 1, 1, 2)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 431, 408))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.md5Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.md5Label.setFont(font)
        self.md5Label.setObjectName("md5Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.md5Label)
        self.md5entry = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.md5entry.setObjectName("md5entry")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.md5entry)
        self.sha1Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sha1Label.setFont(font)
        self.sha1Label.setObjectName("sha1Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sha1Label)
        self.sha1entry = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.sha1entry.setObjectName("sha1entry")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sha1entry)
        self.sha224Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sha224Label.setObjectName("sha224Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sha224Label)
        self.sha224entry = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.sha224entry.setObjectName("sha224entry")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sha224entry)
        self.Sha256Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Sha256Label.setFont(font)
        self.Sha256Label.setObjectName("Sha256Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Sha256Label)
        self.sha256entry = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.sha256entry.setObjectName("sha256entry")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sha256entry)
        self.sha384Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sha384Label.setFont(font)
        self.sha384Label.setObjectName("sha384Label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.sha384Label)
        self.sha384entry = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.sha384entry.setObjectName("sha384entry")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sha384entry)
        self.sha512Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sha512Label.setFont(font)
        self.sha512Label.setObjectName("sha512Label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.sha512Label)
        self.sha512entry = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.sha512entry.setObjectName("sha512entry")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sha512entry)
        self.ripemdLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ripemdLabel.setFont(font)
        self.ripemdLabel.setObjectName("ripemdLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.ripemdLabel)
        self.ripemdentry = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ripemdentry.setObjectName("ripemdentry")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.ripemdentry)
        self.whirlpoolLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.whirlpoolLabel.setFont(font)
        self.whirlpoolLabel.setObjectName("whirlpoolLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.whirlpoolLabel)
        self.whirlpoolEntry = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.whirlpoolEntry.setObjectName("whirlpoolEntry")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.whirlpoolEntry)
        self.shake128Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.shake128Label.setFont(font)
        self.shake128Label.setObjectName("shake128Label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.shake128Label)
        self.shake128entry = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.shake128entry.setObjectName("shake128entry")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.shake128entry)
        self.sm3Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sm3Label.setFont(font)
        self.sm3Label.setObjectName("sm3Label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.sm3Label)
        self.sm3Entry = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.sm3Entry.setObjectName("sm3Entry")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.sm3Entry)
        self.mdc2Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mdc2Label.setFont(font)
        self.mdc2Label.setObjectName("mdc2Label")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.mdc2Label)
        self.mdc2Entry = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.mdc2Entry.setObjectName("mdc2Entry")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.mdc2Entry)
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(14, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.hexLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.hexLabel.setFont(font)
        self.hexLabel.setObjectName("hexLabel")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.hexLabel)
        self.hexentry = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.hexentry.setObjectName("hexentry")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.hexentry)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 8, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MainLabel.setText(_translate("MainWindow", "HashCalc"))
        self.encButton.setText(_translate("MainWindow", "Encryption Tool"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.loadFileLabel.setText(_translate("MainWindow", "Load File:"))
        self.CalculateButton.setText(_translate("MainWindow", "Calculate"))
        self.fileButton.setText(_translate("MainWindow", "Browse..."))
        self.EnterStringLabel.setText(_translate("MainWindow", "Enter String:"))
        self.md5Label.setText(_translate("MainWindow", "md5"))
        self.sha1Label.setText(_translate("MainWindow", "sha1"))
        self.sha224Label.setText(_translate("MainWindow", "sha224"))
        self.Sha256Label.setText(_translate("MainWindow", "sha256"))
        self.sha384Label.setText(_translate("MainWindow", "sha384"))
        self.sha512Label.setText(_translate("MainWindow", "sha512"))
        self.ripemdLabel.setText(_translate("MainWindow", "ripemd160"))
        self.whirlpoolLabel.setText(_translate("MainWindow", "whirlpool"))
        self.shake128Label.setText(_translate("MainWindow", "shake128"))
        self.sm3Label.setText(_translate("MainWindow", "sm3"))
        self.mdc2Label.setText(_translate("MainWindow", "mdc2"))
        self.hexLabel.setText(_translate("MainWindow", "Hex"))


    def calculate(self):
        try:
            my_string = self.textEdit.toPlainText()

            if my_string == '':
                my_string = self.filename[0]
                with open(my_string, 'r') as f:
                	l = f.read()
                my_string = l 
                print(my_string)
    
            self.md5entry.setText(hashes.md5(my_string))
            self.sha1entry.setText(hashes.sha1(my_string))
            self.sha224entry.setText(hashes.sha224(my_string))
            self.sha256entry.setText(hashes.sha256(my_string))
            self.sha384entry.setText(hashes.sha384(my_string))
            self.sha512entry.setText(hashes.sha512(my_string))
            self.shake128entry.setText(hashes.shake128(my_string))
           
            utf = my_string.encode('utf-8')
            hexa = utf.hex()
            self.hexentry.setText(hexa)
            
        except:
           	print("ERROR")
   
    def file_dialogue(self):
        self.filename = QtWidgets.QFileDialog.getOpenFileName()
        print(self.filename[0])
        self.fileLineEdit.setText(self.filename[0])

    def quit(self):
        MainWindow.destroy()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
